var catArray = [

	'Cat Fact #1 : Cats use their tails for balance and have nearly 30 individual bones in them!',
	'Cat Fact #2 : In ancient Egypt killing a cat was a crime punishable by death.',
	'Cat Fact #3 : Did you know that the first cat show was held in 1871 at the Crystal Palace in London? Mee-wow!',
	'Cat Fact #4 : Did you know there are about 100 distinct breeds of domestic cats? Plenty of furry love!',
	'Cat Fact #5 : Cats bury their feces to cover their trails from predators.',
	'Cat Fact #6 : Cats are Americas most popular pets: There are 88 million cats compared to 74 million dogs.',
	'Cat Fact #7 : Some cats have survived falls from over 32 stories onto concrete, due largely to their "Righting reflex."',
	'Cat Fact #8 : Every year, nearly four million cats are eaten in China as a delicacy.',
	'Cat Fact #9 : Cats have 32 Muscles that control the outer ear while humans have only 6.',
	'Cat Fact #10 : A cat has been the mayor of Talkeetna, Alaska for 15 years.',
	'Cat Fact #11 : Cats sleep for 70% of their lives.',
	'Cat Fact #12 : The longest domestic cat ever measured was 48.5 inches when fully streched out.',
	'Cat Fact #13 : The oldest video of cats on youtube dates from 1894. Here it is! https://www.youtube.com/watch?v=r6faUd2fV4U',
	'Cat Fact #14 : A group of cats is called a clowder.',
	'Cat Fact #15 : In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.',
	'Cat Fact #16 : When cats grimace, they are usually “taste-scenting.” They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.',
	'Cat Fact #17 : Cats can’t taste sweetness.',
	'Cat Fact #18 : Owning a cat can reduce the risk of stroke and heart attack by a third.',
	'Cat Fact #19 : Wikipedia has a recording of a cat meowing because why not?',
	'Cat Fact #20 : Evidence suggests domesticated cats have been around since 3600 B.C., 2,000 years before Egypt’s pharaohs.',
	'Cat Fact #21 : A cat’s purr may be a form of self-healing, as it can be a sign of nervousness as well as contentment.',
	'Cat Fact #22 : Similarly, the frequency of a domestic cat’s purr is the same at which muscles and bones repair themselves.',
	'Cat Fact #23 : Adult cats only meow to communicate with humans.',
	'Cat Fact #24 : The world’s richest cat is worth $13 million after his human passed away and left her fortune to him.',
	'Cat Fact #25 : Cats are often lactose intolerant, so stop givin’ them milk!',
	'Cat Fact #26 : The technical term for “hairball” is “bezoar.”',
	'Cat Fact #27 : In the 1960s, the CIA tried to turn a cat into a bonafide spy by implanting a microphone into her ear and a radio transmitter at the base of her skull. She somehow survived the surgery but got hit by a taxi on her first mission.',
	'Cat Fact #28 : Female cats are typically right-pawed while male cats are typically left-pawed.',
	'Cat Fact #29 : Cats make more than 100 different sounds whereas dogs make around 10.',
	'Cat Fact #30 : A cat’s brain is 90% similar to a human’s — more similar than to a dog’s.',
	'Cat Fact #31 : Cats and humans have nearly identical sections of the brain that control emotion.',
	'Cat Fact #32 : A cat’s cerebral cortex (the part of the brain in charge of cognitive information processing) has 300 million neurons, compared with a dog’s 160 million.',
	'Cat Fact #33 : Cats have a longer-term memory than dogs, especially when they learn by actually doing rather than simply seeing.',
	'Cat Fact #34 : Cats have 1,000 times more data storage than an iPad.',
	'Cat Fact #35 : In the 15th century, Pope Innocent VIII began ordering the killing of cats, pronouncing them demonic.',
	'Cat Fact #36 : A cat has five toes on his front paws, and four on the back, unless he’s a polydactyl.',
	'Cat Fact #37 : Polydactyl cats are also referred to as “Hemingway cats” because the author was so fond of them.',
	'Cat Fact #38 : There are 45 Hemingway cats living at the author’s former home in Key West, FL.',
	'Cat Fact #39 : Original kitty litter was made out of sand but it was replaced by more absorbent clay in 1948.',
	'Cat Fact #40 : Abraham Lincoln kept four cats in the White House.',
	'Cat Fact #41 : When asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied “cats.”',
	'Cat Fact #42 : Isaac Newton is credited with inventing the cat door.',
	'Cat Fact #43 : One legend claims that cats were created when a lion on Noah’s Ark sneezed and two kittens came out.',
	'Cat Fact #44 : A cat can jump up to six times its length.',
	'Cat Fact #45 : A house cat is faster than Usain Bolt.',
	'Cat Fact #46 : When cats leave their poop uncovered, it is a sign of aggression to let you know they don’t fear you.',
	'Cat Fact #47 : Cats can change their meow to manipulate a human. They often imitate a human baby when they need food, for example.',
	'Cat Fact #48 : Cats use their whiskers to detect if they can fit through a space.',
	'Cat Fact #49 : Cats only sweat through their foot pads.',
	'Cat Fact #50 : The first cat in space was French. She was named Felicette, or “Astrocat.” She survived the trip.',
	'Cat Fact #51 : Cats have free-floating clavicle bones that attach their shoulders to their forelimbs, which allows them to squeeze through very small spaces.',
	'Cat Fact #52 : Hearing is the strongest of cat’s senses: They can hear sounds as high as 64 kHz — compared with humans, who can hear only as high as 20 kHz.',
	'Cat Fact #53 : Cats can move their ears 180 degrees.',
	'Cat Fact #54 : A cat’s nose is ridged with a unique pattern, just like a human fingerprint.',
	'Cat Fact #55 : Cats have scent glands along their tail, their forehead, lips, chin, and the underside of their front paws.',
	'Cat Fact #56 : Cats lick themselves to get your scent off.',
	'Cat Fact #57 : When a family cat died in ancient Egypt, family members would shave off their eyebrows as they mourned.',
	'Cat Fact #58 : Black cats are bad luck in the United States, but they are good luck in the United Kingdom and Australia.',
	'Cat Fact #59 : Most cats don’t like water because their coats do not insulate them well enough.',
	'Cat Fact #60 : The Egyptian Mau is the oldest breed of cat.',
	'Cat Fact #61 : The Egyptian word for cat is, in fact, “mau.”',
	'Cat Fact #62 : Only 11.5% of people consider themselves “cat people.”',
	'Cat Fact #63 : A cat’s carbon footprint is similar to that of a VW Bug, whereas a dog’s is more like a Hummer.',
	'Cat Fact #64 : When your cat brings home a dead mouse or bird, it may do so to show you that you suck at hunting.',
	'Cat Fact #65 : Cats have inferior daytime sight, but during the night they need seven times less light than humans to see.',
	'Cat Fact #66 : The largest litter of kittens produced 19 kittens.',
	'Cat Fact #67 : Eighty-eight percent of cats in the U.S. are spayed or neutered.',
	'Cat Fact #68 : Only 24% of cats who enter animal shelters are adopted.',
	'Cat Fact #69 : Cats are, in fact, superior to dogs!'
]

module.exports = catArray;